name: news_zone
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  http: ^0.13.5
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  tabbed_sliverlist: ^0.1.0
  buttons_tabbar: ^1.3.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
